# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_data.proto',
  package='org.copdai',
  syntax='proto2',
  serialized_pb=_b('\n\x11sensor_data.proto\x12\norg.copdai\"\xa0\x01\n\x04\x44\x61ta\x12-\n\x0cgeolocations\x18\x01 \x03(\x0b\x32\x17.org.copdai.Geolocation\x12\x31\n\x0e\x61\x63\x63\x65lerometers\x18\x02 \x03(\x0b\x32\x19.org.copdai.Accelerometer\x12(\n\tobstacles\x18\x03 \x03(\x0b\x32\x15.org.copdai.Obstacles\x12\x0c\n\x04time\x18\x19 \x02(\x01\"@\n\x0bGeolocation\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lng\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0c\n\x04time\x18\x19 \x02(\x01\"\x95\x01\n\rAccelerometer\x12\x12\n\nrotation_x\x18\x01 \x02(\x01\x12\x12\n\nrotation_y\x18\x02 \x02(\x01\x12\x12\n\nrotation_z\x18\x03 \x02(\x01\x12\x12\n\nvelocity_x\x18\x08 \x02(\x01\x12\x12\n\nvelocity_y\x18\t \x02(\x01\x12\x12\n\nvelocity_z\x18\n \x02(\x01\x12\x0c\n\x04time\x18\x19 \x02(\x01\"X\n\tObstacles\x12=\n\x15obstacles_coordinates\x18\x01 \x03(\x0b\x32\x1e.org.copdai.ObstacleCoordinate\x12\x0c\n\x04time\x18\x19 \x02(\x01\"\\\n\x12ObstacleCoordinate\x12\n\n\x02x1\x18\x01 \x02(\x01\x12\n\n\x02y1\x18\x02 \x02(\x01\x12\n\n\x02z1\x18\x03 \x02(\x01\x12\n\n\x02x2\x18\x08 \x02(\x01\x12\n\n\x02y2\x18\t \x02(\x01\x12\n\n\x02z2\x18\n \x02(\x01\"<\n\x06\x41\x63tion\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x01 \x02(\x01\x12\x0e\n\x06torque\x18\x02 \x02(\x01\x12\x0c\n\x04time\x18\x19 \x02(\x01')
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='org.copdai.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geolocations', full_name='org.copdai.Data.geolocations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accelerometers', full_name='org.copdai.Data.accelerometers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacles', full_name='org.copdai.Data.obstacles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.copdai.Data.time', index=3,
      number=25, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=194,
)


_GEOLOCATION = _descriptor.Descriptor(
  name='Geolocation',
  full_name='org.copdai.Geolocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='org.copdai.Geolocation.lat', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='org.copdai.Geolocation.lng', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='org.copdai.Geolocation.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.copdai.Geolocation.time', index=3,
      number=25, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=260,
)


_ACCELEROMETER = _descriptor.Descriptor(
  name='Accelerometer',
  full_name='org.copdai.Accelerometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation_x', full_name='org.copdai.Accelerometer.rotation_x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_y', full_name='org.copdai.Accelerometer.rotation_y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_z', full_name='org.copdai.Accelerometer.rotation_z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity_x', full_name='org.copdai.Accelerometer.velocity_x', index=3,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity_y', full_name='org.copdai.Accelerometer.velocity_y', index=4,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity_z', full_name='org.copdai.Accelerometer.velocity_z', index=5,
      number=10, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.copdai.Accelerometer.time', index=6,
      number=25, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=412,
)


_OBSTACLES = _descriptor.Descriptor(
  name='Obstacles',
  full_name='org.copdai.Obstacles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obstacles_coordinates', full_name='org.copdai.Obstacles.obstacles_coordinates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.copdai.Obstacles.time', index=1,
      number=25, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=502,
)


_OBSTACLECOORDINATE = _descriptor.Descriptor(
  name='ObstacleCoordinate',
  full_name='org.copdai.ObstacleCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='org.copdai.ObstacleCoordinate.x1', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='org.copdai.ObstacleCoordinate.y1', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z1', full_name='org.copdai.ObstacleCoordinate.z1', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='org.copdai.ObstacleCoordinate.x2', index=3,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y2', full_name='org.copdai.ObstacleCoordinate.y2', index=4,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z2', full_name='org.copdai.ObstacleCoordinate.z2', index=5,
      number=10, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=596,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='org.copdai.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='org.copdai.Action.acceleration', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='org.copdai.Action.torque', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='org.copdai.Action.time', index=2,
      number=25, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=658,
)

_DATA.fields_by_name['geolocations'].message_type = _GEOLOCATION
_DATA.fields_by_name['accelerometers'].message_type = _ACCELEROMETER
_DATA.fields_by_name['obstacles'].message_type = _OBSTACLES
_OBSTACLES.fields_by_name['obstacles_coordinates'].message_type = _OBSTACLECOORDINATE
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Geolocation'] = _GEOLOCATION
DESCRIPTOR.message_types_by_name['Accelerometer'] = _ACCELEROMETER
DESCRIPTOR.message_types_by_name['Obstacles'] = _OBSTACLES
DESCRIPTOR.message_types_by_name['ObstacleCoordinate'] = _OBSTACLECOORDINATE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.Data)
  ))
_sym_db.RegisterMessage(Data)

Geolocation = _reflection.GeneratedProtocolMessageType('Geolocation', (_message.Message,), dict(
  DESCRIPTOR = _GEOLOCATION,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.Geolocation)
  ))
_sym_db.RegisterMessage(Geolocation)

Accelerometer = _reflection.GeneratedProtocolMessageType('Accelerometer', (_message.Message,), dict(
  DESCRIPTOR = _ACCELEROMETER,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.Accelerometer)
  ))
_sym_db.RegisterMessage(Accelerometer)

Obstacles = _reflection.GeneratedProtocolMessageType('Obstacles', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLES,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.Obstacles)
  ))
_sym_db.RegisterMessage(Obstacles)

ObstacleCoordinate = _reflection.GeneratedProtocolMessageType('ObstacleCoordinate', (_message.Message,), dict(
  DESCRIPTOR = _OBSTACLECOORDINATE,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.ObstacleCoordinate)
  ))
_sym_db.RegisterMessage(ObstacleCoordinate)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:org.copdai.Action)
  ))
_sym_db.RegisterMessage(Action)


# @@protoc_insertion_point(module_scope)
